config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'products#index'

  resources :products, only: [:show, :index]
  resources :orders, only: [:index, :create]

  resource :cart, only: :show do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
    get 'total', to: 'carts#total'
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items

  def total_price
    products.sum(:price)
  end
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :product
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :order_items, dependent: :destroy
  has_many :products, through: :order_items
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :cart_items, dependent: :destroy
  has_many :carts, through: :cart_items
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :cart
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
    product_ids = current_user.cart.try(:product_ids)
    @cart_products = product_ids ? Product.find(product_ids) : []
    @total = current_user.cart.try(:total_price)
  end

  def add
    if cart = current_user.cart
      CartItem.create(cart: cart, product_id: params[:product_id])
    else
      cart = Cart.create(user: current_user)
      cart.cart_items << CartItem.create(product_id: params[:product_id])
    end
    render nothing: true, status: :ok
  end

  def remove
    cart = current_user.cart
    cart_item = cart.cart_items.find_by_product_id(params[:product_id])
    cart_item.destroy
    cart.destroy if cart.cart_items.empty?
    render nothing: true, status: :ok
  end

  def total
    render json: { total: current_user.cart.try(:total_price), status: :ok }
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
    @orders = current_user.orders.includes(:products)
  end

  def create
    order = Order.create(user: current_user)
    current_user.cart.cart_items.each { |ci| OrderItem.create(order: order, product_id: ci.product_id) }
    current_user.cart.destroy
    redirect_to orders_path
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: :show

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @cart_action = current_user.try(:cart) ? (current_user.cart.products.include?(@product) ? "Remove from cart" : "Add to cart") : "Add to cart"
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :description, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/show.html.slim
table
  thead
    tr
      th Title
      th Price
      th

  tbody
    - @cart_products.each do |product|
      tr
        td = product.title
        td.price = product.price
        td.remove = link_to 'Remove from cart', remove_from_cart_path(product), remote: true, method: :put
    tr
      th Total
      th.total = @total
      th
p
  = link_to "Checkout", orders_path, method: :post

app/views/layouts/_nav.html.slim
nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed aria-expanded="false" data-target="#user" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to "Home", root_path, class: "navbar-brand"
    #user.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        - if signed_in?
          li
            = link_to cart_path do
              span.glyphicon.glyphicon-shopping-cart
              span.nav_total
                = current_user.cart.try(:total_price)
          li = link_to "Orders", orders_path
          li = link_to current_user.email, edit_user_registration_path
          li = link_to "Logout", destroy_user_session_path, method: :delete
        - else
          li = link_to "Register", new_user_registration_path
          li = link_to "Login", new_user_session_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Store
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    = render 'layouts/nav'
    .col-md-6.col-md-offset-3
      = yield

app/views/orders/index.html.slim
table
  thead
    tr
      th ID
      th Products

  tbody
    - @orders.each do |order|
      tr
        td = order.id
        td = order.products.map(&:title).join(", ")

app/views/products/index.html.slim
table
  thead
    tr
      th Title
      th Description
      th Price
      th

  tbody
    - @products.each do |product|
      tr
        td = product.title
        td = product.description
        td = product.price
        td = link_to 'Show', product

app/views/products/show.html.slim
p
  strong Title:
  = @product.title
p
  strong Description:
  = @product.description
p
  strong Price:
  = @product.price
p
  - if signed_in?
    = link_to "", class: "button", data: {action: @cart_action, addUrl: add_to_cart_path(@product), removeUrl: remove_from_cart_path(@product)} do
      span.glyphicon.glyphicon-shopping-cart
      span.action
        = @cart_action

= link_to 'Back', products_path